export { ensureTemplateNotStale } from "./expire";
export {
  TEMPLATE_STATUSES,
  TEMPLATE_STATUS_LABELS,
  EXPIRATION_MODES,
  acceptsSignatures,
  computeExpiresAt,
  effectiveTemplateStatus,
  formatExpiresAt,
  isExpirationMode,
  isTemplateStatus,
  type ExpirationMode,
  type TemplateLifecycle,
  type TemplateStatus,
} from "./status";
export {
  SIGNATURE_TIMEZONES,
  WEEKDAY_LABELS_FR,
  configFromTemplateRow,
  formatSignatureHoursSummary,
  formatTimeFr,
  isWithinSignatureHours,
  isValidTimezone,
  normalizeTimeInput,
  parseTimeToMinutes,
  describeNextSignatureOpen,
  signatureHoursClosedCopy,
  signatureHoursClosedMessage,
  type SignatureHoursClosedCopy,
  type SignatureHoursConfig,
} from "./hours";
